language: go

sudo: false

go_import_path: github.com/xetys/hetzner-kube

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

go_import_path: github.com/xetys/hetzner-kube

before_install:
  - openssl aes-256-cbc -K $ENCRYPTED_IR_RSA_PUB_KEY -iv $ENCRYPTED_IR_RSA_PUB_IV -in tests/id_rsa.pub.enc -out tests/id_rsa.pub -d
  - openssl aes-256-cbc -K $ENCRYPTED_IR_RSA_PRV_KEY -iv $ENCRYPTED_IR_RSA_PRV_IV -in tests/id_rsa.enc     -out tests/id_rsa     -d
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint
  - go get -u honnef.co/go/tools/...
  - go get -u mvdan.cc/unparam
  - go get -u github.com/client9/misspell/cmd/misspell
  - dep ensure

script:
  - go test -v ./...

jobs:
  include:
    - stage: Linting
      script:
        - golint $(go list ./...)
        - unused $(go list ./...)
        - gosimple $(go list ./...)
        - misspell -error $(git ls-files | grep -v vendor/)
        - unparam $(go list ./...)
        - staticcheck $(go list ./...)
      go: 1.11.x

    - stage: e2e test
      script:
        - go build
        - make info
        - make context
        - make ssh-key
        - make cluster
        - make cleanup
      go: 1.11.x
