language: go

sudo: false

go_import_path: github.com/xetys/hetzner-kube

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint
  - go get -u honnef.co/go/tools/...
  - go get -u mvdan.cc/unparam
  - go get -u github.com/client9/misspell/cmd/misspell
  - dep ensure

after_script:
  - make hard-cleanup

script:
  - go test -v ./...

jobs:
  include:
    - stage: Linting
      script:
        - golint $(go list ./...)
        - unused $(go list ./...)
        - gosimple $(go list ./...)
        - misspell -error $(git ls-files | grep -v vendor/)
        - unparam $(go list ./...)
        - staticcheck $(go list ./...)
      go: 1.11.x

    - stage: e2e test
      script:
        - go build
        - make preparare
        - make test-all
        - make cleanup
      go: 1.11.x
