language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint
  - go get -u honnef.co/go/tools/...
  - go get -u mvdan.cc/unparam
  - go get -u github.com/client9/misspell/cmd/misspell
  - dep ensure

script:
  - golint cmd/ pkg/
  - go test -v ./...
  - unused $(go list ./...)
  - gosimple $(go list ./...)
  - misspell -error $(git ls-files | grep -v vendor/)
  - unparam $(go list ./...)
  - staticcheck $(go list ./...)
