language: go

sudo: false

install: true

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - tip

after_script:
  - make hard-cleanup

script:
  - go test -v ./...

jobs:
  include:
    - stage: E2E testing
      script:
        - go build
        - make preparare
        - make test-all
        - make cleanup
      go: 1.11.x
      if: fork = false

    - stage: Build
      script:
        - make build
      go: 1.11.x
      if: tag IS present

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: yes
  file: dist/*
  name: $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
